import { Clinic } from "@/types";

export const clinics: Clinic[] = [
  {
    id: 1,
    name: "Acıbadem Fulya Sağlık Merkezi",
    category: "Genel Hastane",
    city: "İstanbul",
    district: "Fulya",
    specialties: ["Kardiyoloji", "Nöroloji", "Ortopedi"],
    rating: 4.7,
    reviewCount: 1120,
    priceRange: "$$$",
    image: "/clinics/acibadem-fulya.jpg",
    description:
      "Uluslararası standartlarda teşhis ve tedavi, 24/7 acil servis.",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce", "Arapça"],
    services: [
      { name: "Bypass Ameliyatı", priceRange: "20.000€ - 30.000€" },
      { name: "Artroplasti", priceRange: "8.000€ - 12.000€" },
    ],
  },
  {
    id: 2,
    name: "Medical Park Göztepe Hastanesi",
    category: "Göz",
    city: "İstanbul",
    district: "Göztepe",
    specialties: ["Katarakt", "Lazer Cerrahi", "Retina"],
    rating: 4.6,
    reviewCount: 890,
    priceRange: "$$",
    image: "/clinics/medical-park-goztepe.jpg",
    description: "Son teknoloji lazer cihazlarıyla konforlu göz tedavisi.",
    accreditations: ["ISO 13485"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Katarakt Cerrahisi", priceRange: "1.200€ - 2.000€" },
      { name: "Refraktif Cerrahi", priceRange: "1.500€ - 2.500€" },
    ],
  },
  {
    id: 3,
    name: "Liv Hospital Ankara",
    category: "Genel Hastane",
    city: "Ankara",
    district: "Çankaya",
    specialties: ["Onkoloji", "Kardiyoloji", "Nöroşirürji"],
    rating: 4.8,
    reviewCount: 950,
    priceRange: "$$$",
    image: "/clinics/liv-ankara.jpg",
    description:
      "Modern tıp teknolojileri ile donatılmış, uluslararası standartlarda hizmet.",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce", "Almanca"],
    services: [
      { name: "Kemoterapi", priceRange: "3.500€ - 6.000€" },
      { name: "Açık Kalp Cerrahisi", priceRange: "25.000€ - 35.000€" },
    ],
  },
  {
    id: 4,
    name: "Ege Sağlık Hastanesi",
    category: "Genel Hastane",
    city: "İzmir",
    district: "Bornova",
    specialties: ["Kadın Hastalıkları", "Kardiyoloji", "Cerrahi"],
    rating: 4.4,
    reviewCount: 680,
    priceRange: "$$",
    image: "/clinics/ege-saglik.jpg",
    description: "Ege bölgesinin lider sağlık merkezi, modern servisler.",
    accreditations: ["ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Sezaryen Doğum", priceRange: "2.000€ - 3.500€" },
      { name: "Bypass Ameliyatı", priceRange: "18.000€ - 28.000€" },
    ],
  },
  {
    id: 5,
    name: "Acıbadem Bursa Hastanesi",
    category: "Genel Hastane",
    city: "Bursa",
    district: "Nilüfer",
    specialties: ["Estetik", "Dermatoloji", "Endokrinoloji"],
    rating: 4.6,
    reviewCount: 540,
    priceRange: "$$",
    image: "/clinics/acibadem-bursa.jpg",
    description: "Estetik ve sağlık hizmetlerinde bölge lideri.",
    accreditations: ["JCI", "ISO 9001"],
    languages: ["Türkçe", "İngilizce"],
    services: [
      { name: "Rinoplasti", priceRange: "3.000€ - 5.000€" },
      { name: "Hormonal Tedavi", priceRange: "800€ - 1.200€" },
    ],
  },
  {
    id: 6,
    name: "Medical Park Antalya Hastanesi",
    category: "Genel Hastane",
    city: "Antalya",
    district: "Muratpaşa",
    specialties: ["Ortopedi", "Diş", "Fizyoterapi"],
    rating: 4.7,
    reviewCount: 870,
    priceRange: "$$$",
    image: "/clinics/medical-park-antalya.jpg",
    description: "Turistik lokasyonda, profesyonel sağlık hizmetleri.",
    accreditations: ["JCI"],
    languages: ["Türkçe", "İngilizce", "Rusça"],
    services: [
      { name: "Diz Protezi", priceRange: "10.000€ - 15.000€" },
      { name: "Diş İmplantı", priceRange: "700€ - 1.500€" },
    ],
  },
];
